name: example
description: Example for micha_core
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=3.22.2"
dependencies:
  flutter:
    sdk: flutter
  micha_core:
    path: ../
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
