name: micha_core
description: Extensions, widgets and other utilities that are missing in Flutter's SDK.
version: 1.1.0
repository: https://github.com/michasng/micha_core
environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=3.32.8"
dependencies:
  flutter:
    sdk: flutter
  logging: ^1.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
