name: micha_core
description: Extensions, widgets and other utilities that are missing in Flutter's SDK.
version: 1.0.0
repository: https://github.com/michasng/micha_core
environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=3.22.2"
dependencies:
  flutter:
    sdk: flutter
  logging: ^1.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
